### ISSUE TITLE
exec /bin/drone-helm: no such file or directory

### ISSUE THREAD

**Issue by MartinLau7** [pelotech/drone-helm3#111]
**My drone-helm3 and drone versions:**

**What I tried to do:**

`run drone deploy 2 k8s`

**What happened:**

`error: exec /bin/drone-helm: no such file or directory`

**More info:**

```log
latest: Pulling from pelotech/drone-helm3
Digest: sha256:8ea82c70aa3079218ec6cacd2482af91347341f1eb008637064795d006084092
Status: Image is up to date for pelotech/drone-helm3:latest
exec /bin/drone-helm: no such file or directory
```

**Comment by VengefulAncient** [comment]
Same issue here. Please roll back whatever changes were made yesterday, this is probably affecting thousands of users.

**Comment by josmo** [comment]
My apologies about that all, I should have given it a quick test myself - I've retagged latest from 0.14.5 so that it minimizes downtime for folks - as @VengefulAncient mentioned using the 0.14.5 tag vs latest is usually a good idea anyways to allow for breaking changes (although this isn't that and just a broken change all together) - I'll leave this issue open until the root issue is fixed

**Comment by josmo** [comment]
Ok, looks like it was an issue with CGO - I've pushed a change where latest, 0.15, 0.15.1 should all now be good to go and up to date. Feel free to let me know if there's any more issues moving forward.
